### ISSUE TITLE
Not able to receive data from all the plugins when more than one plugin directory exists

### ISSUE THREAD

**Issue by kunaldeo** [samrg472/plugins.dart#5]
When I have two plugin directories using listenAll, I am only able to receive data from one plugin and not both. 
```
Received data in plugin2: Hello from loader!
Received data in plugin: Hello from loader!
Received data from plugin 'test2': More info from plugin 2
```

**Comment by kunaldeo** [comment]
I think pm.plugins can be used to fetch the names of the plugins loaded and then call pm.listen individually.

**Comment by samrg472** [comment]
Are you using `loadAll()` or individually loading the plugins via `load()`?

**Comment by kunaldeo** [comment]
Tried both.

**Comment by samrg472** [comment]
I can't replicate the issue. I receive data from all plugins. I have uploaded some sample code in which the plugin manager can receive data from all plugins without issues.
https://drive.google.com/file/d/0Bx8_f87CnjeUOUNGbGF5RXFSUGc

**Comment by kunaldeo** [comment]
I got the issue. I didn't remove the pm.killAll statement from your sample on pub. 
BTW: Looks like you are updating the plugin layout when it will be live on pub .

**Comment by samrg472** [comment]
It will be live when the features of plugin loading from the pub cache is complete.

**Comment by kunaldeo** [comment]
Cool looking forward to that.
